DROP SCHEMA if exists sample_test;
CREATE SCHEMA sample_test;

-- CREATE TABLES
CREATE TABLE sample_test.ACCOUNT (
  ID INT(11) NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(100) NOT NULL,
  EMAIL VARCHAR(255) NOT NULL,
  FIRST_NAME VARCHAR(255) NOT NULL,
  LAST_NAME VARCHAR(255) NOT NULL,
  CREATED_AT DATETIME NULL,
  CREATED_BY VARCHAR(255) NULL,
  UPDATED_AT DATETIME NULL,
  UPDATED_BY VARCHAR(255) NULL,
  VERSION INT(11) NOT NULL,
  PRIMARY KEY (ID),
  UNIQUE INDEX ID_UNIQUE (ID ASC),
  UNIQUE INDEX ACCOUNT_UQ_1 (NAME ASC),
  UNIQUE INDEX ACCOUNT_UQ_2 (EMAIL ASC)
 );

 INSERT sample_test.ACCOUNT(ID, NAME, EMAIL, FIRST_NAME, LAST_NAME) VALUES(NULL, 'test', 'test@gmail.com', 'TestFirstName', 'TestLastName');